version: '3.8'

services:
  mcp-codeanalysis:
    build: .
    container_name: mcp-code-analysis
    network_mode: host
    environment:
      - NODE_ENV=production
      - PORT=3005
      - REDIS_URL=redis://localhost:6379
    restart: unless-stopped
    volumes:
      - ./data:/usr/src/app/data

networks:
  localai_default:
    external: true
